# Generated by Django 4.1.4 on 2023-01-07 12:53

from django.db import migrations, models
import loginapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fKcheck",
                    models.CharField(default=loginapp.models.UUIDrand, max_length=36),
                ),
                ("Rstate", models.CharField(max_length=42)),
                ("Raccesscode", models.CharField(max_length=43)),
            ],
        ),
    ]
