# Generated by Django 4.1.4 on 2023-01-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="login",
            old_name="fKcheck",
            new_name="FKcheck",
        ),
    ]
