# Generated by Django 4.1.4 on 2023-01-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0003_udata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="Raccesscode",
        ),
    ]
