# Generated by Django 4.1.4 on 2023-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0005_remove_udata_upic_udata_uaddress_udata_uphone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="udata",
            name="uphone",
            field=models.IntegerField(default=0, null=True, verbose_name="聯絡電話"),
        ),
    ]
