# Generated by Django 4.1.4 on 2023-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0002_order_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_detail",
            name="C_amount",
            field=models.IntegerField(null=True, verbose_name="花費碳排總量"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="drymode",
            field=models.CharField(max_length=20, null=True, verbose_name="烘衣模式"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="foldmode",
            field=models.CharField(max_length=20, null=True, verbose_name="摺衣模式"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="mState",
            field=models.CharField(max_length=10, null=True, verbose_name="洗衣狀態"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="oPoint",
            field=models.IntegerField(null=True, verbose_name="總點數"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="oReceivecode",
            field=models.CharField(max_length=30, null=True, verbose_name="取件條碼"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="oSendcode",
            field=models.CharField(max_length=30, null=True, verbose_name="寄件條碼"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="oTotal",
            field=models.IntegerField(null=True, verbose_name="總金額"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="oTransport",
            field=models.CharField(max_length=10, null=True, verbose_name="運送方式"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="orderId",
            field=models.CharField(max_length=20, null=True, verbose_name="訂單編號"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="sId",
            field=models.CharField(max_length=10, null=True, verbose_name="店鋪標號"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="spinmode",
            field=models.CharField(max_length=20, null=True, verbose_name="脫水模式"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="washmode",
            field=models.CharField(max_length=20, null=True, verbose_name="洗衣模式"),
        ),
    ]
