# Generated by Django 4.1.4 on 2023-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0003_alter_order_detail_c_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="ttime",
            field=models.CharField(max_length=20, verbose_name="所需時間"),
        ),
    ]
