# Generated by Django 4.1.4 on 2023-01-11 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0005_alter_price_ttime"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_c",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ORDID",
                    models.CharField(max_length=20, null=True, verbose_name="訂單編號"),
                ),
                ("MEMID", models.CharField(max_length=10, verbose_name="使用者編號")),
                ("C_AMOUNT", models.IntegerField(null=True, verbose_name="花費碳排總量")),
                ("GPOINT", models.IntegerField(null=True, verbose_name="總點數")),
                ("AMOUNT", models.IntegerField(null=True, verbose_name="總金額")),
                (
                    "CDATE",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="成立時間"
                    ),
                ),
            ],
        ),
    ]
