# Generated by Django 4.1.4 on 2023-01-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0006_order_c"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order_c",
        ),
    ]
