# Generated by Django 4.1.4 on 2023-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0007_delete_order_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="finaltime",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="預定完成時間"
            ),
        ),
    ]
