# Generated by Django 4.1.4 on 2023-01-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0008_order_detail_finaltime"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="wpoint",
            field=models.IntegerField(null=True, verbose_name="智慧喜點數"),
        ),
    ]
