# Generated by Django 4.1.4 on 2023-01-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0009_order_detail_wpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="wash_num",
            field=models.IntegerField(null=True, verbose_name="送洗桶數"),
        ),
    ]
