# Generated by Django 4.1.4 on 2023-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0010_order_detail_wash_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_detail",
            name="C_amount",
            field=models.IntegerField(null=True, verbose_name="花費碳稅"),
        ),
    ]
