# Generated by Django 4.1.4 on 2023-01-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0011_alter_order_detail_c_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_detail",
            name="C_tax",
            field=models.IntegerField(null=True, verbose_name="碳稅"),
        ),
        migrations.AlterField(
            model_name="order_detail",
            name="C_amount",
            field=models.IntegerField(null=True, verbose_name="花費碳排總量"),
        ),
    ]
