# Generated by Django 4.1.4 on 2023-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0012_order_detail_c_tax_alter_order_detail_c_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="oFinish",
            field=models.DateTimeField(verbose_name="完成時間"),
        ),
    ]
