# Generated by Django 4.1.4 on 2023-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("washapp", "0013_alter_order_ofinish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="oFinish",
            field=models.DateTimeField(null=True, verbose_name="完成時間"),
        ),
    ]
